### PR TITLE
Add YAML linter

### PR DESCRIPTION
**Pull request by thinkl33t**
Add a yaml linter, and tweak existing files to pass linting.

Closes: #10

### CODE REVIEW

**Review by abdullahgarcia — APPROVED** [review]
LGTM

**Comment by abdullahgarcia** [comment]
@thinkl33t can you please address the conflict?

**Comment by eddie-knight** [comment]
We'll need to get this added to the child module template also, IMO

**Comment by eddie-knight** [comment]
This is good to merge after the conflict is resolved. Sorry for leaving it unattended so long 👎

**Pull request merged**
