### PR TITLE
Initial port of github actions from CFI

### LINKED ISSUE #9: Move spin-up / teardown CI across to this repo
### Description of Problem:

We need to be running full end-to-end smoke tests of the EKS IaC on dev.

- [x] get aws keys added to this repo
- [x] move github actions from main CFI repo
- [ ] test and update as needed

### PR DESCRIPTION
**Pull request by thinkl33t**
Currently excludes the probr check & badges, as they are contained in a  different repo and we'll need to chat with the testing team to figure  out where they're going to live longer-term.

Closes #9

### CODE REVIEW

**Comment by thinkl33t** [comment]
Github actions are working correctly, creating and shutting down the cluster - looks like we have some issues with our aws eks module being out of date though.

**Comment by thinkl33t** [comment]
https://github.com/finos/compliant-financial-infrastructure/pull/319 removes them from CFI main

**Comment by AdrianHammond** [comment]
Parked will further research on testing framework completed by @ml4 @thinkl33t once agreed  this should be created as a template.

**Comment by eddie-knight** [comment]
Corrected actions errors related to porting. Final pipeline failure is related to EKS upgrade & can be left for another PR.

**Pull request merged**
